{{ range $mod := .Modules }}
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: {{ $mod.Name }}
spec:
  replicas: {{ propertyOr $mod "replicas" 1}}
  template:
    metadata:
      labels:
        app: {{ $mod.Name }}
    spec:
      containers:
      - name: nanosvc
        image: {{ index $.Env "DOCKER_REGISTRY"}}/{{ $mod.Name }}:{{ $mod.Version }}
        ports:
        - containerPort: {{ property $mod "expose" }}
        args:
        - name="{{ $mod.Name }}"
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: {{ $mod.Name }}
spec:
  selector:
    app: {{ $mod.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ property $mod "expose" }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $mod.Name }}
spec:
  rules:
  - http:
      paths:
      - path: {{ property $mod "url" }}
        backend:
          serviceName: {{ $mod.Name }}
          servicePort: 80
{{ end }} 
